server:
    compression.enabled: true
spring:
    servlet.multipart.max-file-size: 5MB 
    resources:
        cache.cachecontrol.max-age: 3600
        static-locations: classpath:/static/ ,  file:///d:/static/
    freemarker:
        prefix: /
        suffix: .html
    mvc.view:
        prefix: /
        suffix: .html
    jpa:
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy   
    datasource:
        url: jdbc:mysql://localhost/test
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
        date-format:  yyyy-MM-dd HH:mm:ss
        time-zone: Asia/Kathmandu
        default-property-inclusion: NON_NULL
        serialization:
            INDENT_OUTPUT: false
app:
    images: d:/static/images/